server.port=8081

# Apuntamos al puerto 5434 y a las nuevas credenciales
spring.datasource.url=jdbc:postgresql://localhost:5434/subscrybe_pro
spring.datasource.username=admin_pro
spring.datasource.password=root123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true